import { SkillBar } from "./SkillBar.js";
import { TargetFrame } from "./TargetFrame.js";

export class HUD {
  constructor(scene,engine,player,entities,skillSystem,progression,onSkill){this.scene=scene;this.engine=engine;this.player=player;this.entities=entities;this.progression=progression;this.root=document.getElementById("hud");this.hpBar=document.getElementById("player-hp-bar");this.hpText=document.getElementById("player-hp-text");this.manaBar=document.getElementById("player-mana-bar");this.manaText=document.getElementById("player-mana-text");this.level=document.getElementById("player-level");this.xpBar=document.getElementById("player-xp-bar");this.xpText=document.getElementById("player-xp-text");this.fps=document.getElementById("debug-fps");this.questPanel=document.querySelector(".quest-panel");this.quest=document.getElementById("quest-status");this.statusMessage="";this.statusUntil=0;this.toast=document.getElementById("progress-toast");this.toastTimer=0;this.targetFrame=new TargetFrame(document.getElementById("target-frame"));this.skillBar=new SkillBar(document.getElementById("skill-bar"),onSkill);this.skillSystem=skillSystem;this.labelLayer=document.getElementById("world-labels");this.damageLayer=document.getElementById("damage-layer");this.labels=new Map();this.damagePool=this.#createDamagePool();this.damageCursor=0;for(const mob of entities.mobs)this.#labelFor(mob);}
  show(value=true){this.root.hidden=!value;}
  setDebug(value){this.fps.hidden=!value;}
  setStatus(message){this.statusMessage=message;this.statusUntil=performance.now()+2400;this.quest.textContent=message;}
  showDamage(entity,result){const node=this.damagePool[this.damageCursor++%this.damagePool.length],point=entity.position.add(new BABYLON.Vector3(0,2.1,0)),screen=this.#project(point);node.textContent=result.critical?`${result.amount}!`:String(result.amount);node.className=`damage-number${result.critical?" critical":""}`;node.style.left=`${screen.x}px`;node.style.top=`${screen.y}px`;node.hidden=false;node.style.animation="none";void node.offsetWidth;node.style.animation="";setTimeout(()=>node.hidden=true,920);}
  announceProgress(result){const parts=[`+${result.totalXp} XP`];if(result.questCompleted)parts.unshift("İlk Sınav tamamlandı");if(result.levelsGained)parts.push(`Seviye ${result.level}`);this.toast.textContent=parts.join(" • ");this.toast.hidden=false;this.toast.classList.remove("is-visible");void this.toast.offsetWidth;this.toast.classList.add("is-visible");clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>{this.toast.hidden=true;this.toast.classList.remove("is-visible");},2600);}
  update(){const p=this.player,progress=this.progression.snapshot(),quest=progress.quest;this.hpBar.style.width=`${Math.max(0,p.health/p.maxHealth)*100}%`;this.hpText.textContent=`${Math.ceil(p.health)} / ${p.maxHealth}`;this.manaBar.style.width=`${Math.max(0,p.mana/p.maxMana)*100}%`;this.manaText.textContent=`${Math.floor(p.mana)} / ${p.maxMana}`;this.level.textContent=progress.level;this.xpBar.style.width=`${Math.min(100,progress.xp/progress.nextLevelXp*100)}%`;this.xpText.textContent=`${progress.xp} / ${progress.nextLevelXp} XP`;const questText=quest.completed?`Tamamlandı • +${quest.rewardXp} XP`:`Yaratıkları yen: ${quest.progress} / ${quest.goal}`;this.quest.textContent=performance.now()<this.statusUntil?this.statusMessage:questText;this.questPanel.classList.toggle("is-complete",quest.completed);this.targetFrame.update(this.entities.selected);this.skillBar.update(this.skillSystem,p);this.fps.textContent=`${this.engine.getFps().toFixed(0)} FPS`;for(const mob of this.entities.mobs){const node=this.labels.get(mob.id);node.hidden=!mob.alive;if(!mob.alive)continue;const screen=this.#project(mob.position.add(new BABYLON.Vector3(0,2.45,0)));node.style.left=`${screen.x}px`;node.style.top=`${screen.y}px`;node.style.opacity=screen.z>0&&screen.z<1?"1":"0";node.classList.toggle("selected",this.entities.selected===mob);node.querySelector("i").style.width=`${mob.health/mob.maxHealth*100}%`;}}
  #labelFor(mob){const node=document.createElement("div");node.className="mob-label";node.innerHTML=`<strong>${mob.name}</strong><small>Seviye ${mob.level}</small><div class="bar"><i></i></div>`;this.labelLayer.append(node);this.labels.set(mob.id,node);}
  #createDamagePool(){return Array.from({length:18},()=>{const node=document.createElement("span");node.className="damage-number";node.hidden=true;this.damageLayer.append(node);return node;});}
  #project(position){const width=this.engine.getRenderWidth(),height=this.engine.getRenderHeight(),viewport=this.scene.activeCamera.viewport.toGlobal(width,height);const projected=BABYLON.Vector3.Project(position,BABYLON.Matrix.IdentityReadOnly,this.scene.getTransformMatrix(),viewport);const rect=this.engine.getRenderingCanvas().getBoundingClientRect();return{x:projected.x/width*rect.width+rect.left,y:projected.y/height*rect.height+rect.top,z:projected.z};}
}
