import { EngineRuntime } from "./core/Engine.js";
import { Game } from "./core/Game.js";

const canvas=document.getElementById("game-canvas"),menu=document.getElementById("menu-screen"),loading=document.getElementById("loading-screen"),label=document.getElementById("loading-label"),bar=document.getElementById("loading-bar"),percent=document.getElementById("loading-percent"),fatal=document.getElementById("fatal-error");let runtime=null,game=null,starting=false;
function progress(value,message){const safe=Math.max(0,Math.min(100,Math.round(value)));bar.style.width=`${safe}%`;percent.textContent=`${safe}%`;label.textContent=message;}
function showError(error){console.error("[Tora Online] Başlatma hatası",error);loading.hidden=true;fatal.hidden=false;fatal.querySelector("span").textContent=error?.message||"Bilinmeyen bir başlatma hatası oluştu.";window.ToraMenu?.unlock();starting=false;}
async function enter(quality){if(starting)return;starting=true;loading.hidden=false;progress(3,"Kadim geçit açılıyor…");try{if(!game){runtime=await EngineRuntime.create(canvas,quality,progress);game=new Game(runtime,progress);const result=await Promise.race([game.initialize(),new Promise((_,reject)=>setTimeout(()=>reject(new Error("Oyun hazırlığı zaman aşımına uğradı.")),90000))]);console.info(`[Tora Online] ${result.backend}; zorunlu GLB varlık seti doğrulandı.`);}else game.applyQuality(quality);progress(100,"Dünya hazır.");await new Promise(resolve=>setTimeout(resolve,280));menu.classList.add("is-leaving");loading.hidden=true;game.enter();starting=false;}catch(error){showError(error);}}
document.addEventListener("tora:enter",event=>enter(event.detail.quality));document.addEventListener("tora:quality",event=>game?.applyQuality(event.detail.quality));
addEventListener("error",event=>console.error("[Tora Online] Çalışma zamanı hatası:",event.error||event.message));addEventListener("unhandledrejection",event=>console.error("[Tora Online] Promise hatası:",event.reason));
