const $=id=>document.getElementById(id);
const canvas=$("render-canvas"),bootScreen=$("boot-screen"),deployButton=$("deploy-button"),bootStatus=$("boot-status"),hud=$("hud"),resultScreen=$("result-screen"),replayButton=$("replay-button"),pauseButton=$("pause-button"),interaction=$("interaction"),feed=$("feed"),hitMarker=$("hit-marker"),damageVignette=$("damage-vignette"),reloadIndicator=$("reload-indicator"),waveBanner=$("wave-banner"),waveBannerTitle=$("wave-banner-title"),waveBannerText=$("wave-banner-text");
const labels={heading:$("heading"),objectiveTitle:$("objective-title"),objectiveText:$("objective-text"),killCount:$("kill-count"),killTarget:$("kill-target"),objectiveProgress:$("objective-progress"),playerLevel:$("player-level"),healthValue:$("health-value"),healthBar:$("health-bar"),armorValue:$("armor-value"),armorBar:$("armor-bar"),weaponRarity:$("weapon-rarity"),weaponName:$("weapon-name"),ammoCurrent:$("ammo-current"),ammoReserve:$("ammo-reserve"),xpLabel:$("xp-label"),xpBar:$("xp-bar"),resultTitle:$("result-title"),resultText:$("result-text"),resultKills:$("result-kills"),resultLevel:$("result-level"),resultWeapon:$("result-weapon")};
window.addEventListener("error",event=>{document.body.dataset.gameError=event.message||"asset-error";if(!document.body.dataset.gameReady)bootStatus.textContent="Oyun yüklenirken hata oluştu · Sayfayı yenileyip tekrar dene."});

const LOADOUT=[
  {slot:1,kind:"rifle",name:"RAVEN AR-4",rarity:"OPERATÖR",color:"#66e3ee",damage:34,fireRate:9.2,mag:30,ammo:30,reserve:150,spread:.0048,range:150,speed:.53,auto:true,mode:"OTOMATİK · 5.56"},
  {slot:2,kind:"pistol",name:"KITE P-9",rarity:"TAKTİK",color:"#ffcb57",damage:52,fireRate:4.8,mag:15,ammo:15,reserve:75,spread:.0032,range:90,speed:.69,auto:false,mode:"YARI OTOMATİK · 9MM"},
  {slot:3,kind:"knife",name:"VANTA KNIFE",rarity:"YAKIN DÖVÜŞ",color:"#ff5b35",damage:145,fireRate:1.55,mag:0,ammo:0,reserve:0,spread:0,range:2.75,speed:.79,auto:false,mode:"BIÇAK · HIZLI KOŞU"},
];
const WAVES=[
  {count:5,weights:[1,0,0],label:"UYANIŞ"},
  {count:7,weights:[.72,.28,0],label:"İLK HÜCUM"},
  {count:9,weights:[.57,.35,.08],label:"KARANLIK SÜRÜ"},
  {count:12,weights:[.43,.42,.15],label:"KIRILMA NOKTASI"},
  {count:15,weights:[.3,.48,.22],label:"SON İSTİLA"},
];
const ZOMBIE_TYPES={
  walker:{name:"YÜRÜYEN",health:95,speed:1.8,damage:13,scale:1,color:"#4f5d4c"},
  runner:{name:"KOŞUCU",health:72,speed:3.1,damage:10,scale:.92,color:"#625346"},
  brute:{name:"İRİ",health:250,speed:1.35,damage:25,scale:1.28,color:"#453f39"},
};
const state={running:false,paused:true,ended:false,firing:false,reloading:false,health:100,armor:65,level:1,xp:0,xpNeeded:100,totalKills:0,waveIndex:-1,waveKills:0,waveTarget:0,waveActive:false,spawnRemaining:0,spawnTimer:0,intermission:0,currentSlot:0,lastShot:0,elapsed:0,recoil:0,switchTimer:0,meleeTimer:0,reloadTimer:0,enemies:[],loot:[],nearestLoot:null,extraction:null,damageFlashTimer:0};
const keys={shift:false};

if(!window.BABYLON||!BABYLON.Engine.isSupported()){bootStatus.textContent="3B motor başlatılamadı. WebGL destekli güncel bir tarayıcı kullan.";deployButton.disabled=true;throw new Error("Babylon.js veya WebGL kullanılamıyor.");}
const engine=new BABYLON.Engine(canvas,true,{preserveDrawingBuffer:true,stencil:true,adaptToDeviceRatio:true});
if(devicePixelRatio>1.5)engine.setHardwareScalingLevel(devicePixelRatio/1.55);
const scene=new BABYLON.Scene(engine);scene.clearColor=new BABYLON.Color4(.025,.045,.065,1);scene.ambientColor=new BABYLON.Color3(.12,.16,.18);scene.fogMode=BABYLON.Scene.FOGMODE_EXP2;scene.fogDensity=.0046;scene.fogColor=new BABYLON.Color3(.06,.085,.1);scene.collisionsEnabled=true;scene.gravity=new BABYLON.Vector3(0,-.42,0);
const camera=new BABYLON.UniversalCamera("operator",new BABYLON.Vector3(0,2.05,-70),scene);camera.minZ=.07;camera.maxZ=360;camera.fov=1.03;camera.speed=.53;camera.inertia=.16;camera.angularSensibility=2250;camera.applyGravity=true;camera.checkCollisions=true;camera.ellipsoid=new BABYLON.Vector3(.5,.9,.5);camera.ellipsoidOffset=new BABYLON.Vector3(0,.9,0);camera.keysUp.push(87);camera.keysDown.push(83);camera.keysLeft.push(65);camera.keysRight.push(68);camera.attachControl(canvas,true);

function makeMat(name,color,{metal=.05,rough=.8,emissive=0,alpha=1}={}){const m=new BABYLON.PBRMaterial(name,scene);m.albedoColor=BABYLON.Color3.FromHexString(color);m.metallic=metal;m.roughness=rough;m.alpha=alpha;m.environmentIntensity=.72;if(emissive)m.emissiveColor=BABYLON.Color3.FromHexString(color).scale(emissive);return m;}
const mats={concrete:makeMat("concrete","#343e41",{rough:.94}),asphalt:makeMat("asphalt","#1b252a",{rough:.88}),wall:makeMat("wall","#3b474c",{metal:.35,rough:.7}),dark:makeMat("dark-steel","#121a1f",{metal:.85,rough:.28}),orange:makeMat("warning","#d8492e",{metal:.35,rough:.62,emissive:.1}),cyan:makeMat("signal","#55d6df",{metal:.2,rough:.3,emissive:.55}),glass:makeMat("glass","#487887",{metal:.2,rough:.12,alpha:.48}),rubber:makeMat("rubber","#080909",{rough:.98}),wood:makeMat("wood","#5a4530",{rough:.96}),skin:makeMat("dead-skin","#7c826d",{rough:.9}),blood:makeMat("blood","#681b14",{rough:.65}),cloth:makeMat("cloth","#303833",{rough:1}),glove:makeMat("operator-glove","#1a2228",{metal:.1,rough:.72}),gun:makeMat("gun-metal","#26343b",{metal:.92,rough:.22}),gun2:makeMat("gun-polymer","#354247",{metal:.2,rough:.64}),brass:makeMat("brass","#a98549",{metal:.9,rough:.26}),blade:makeMat("blade","#c3d0d5",{metal:1,rough:.1})};

function loadSurface(file,scale=3){const texture=new BABYLON.Texture(`assets/textures/${file}`,scene,false,true,BABYLON.Texture.TRILINEAR_SAMPLINGMODE);texture.wrapU=texture.wrapV=BABYLON.Texture.WRAP_ADDRESSMODE;texture.uScale=texture.vScale=scale;texture.anisotropicFilteringLevel=8;return texture;}
function proceduralSurface(name,base,accent,kind="speckle",scale=3){const texture=new BABYLON.DynamicTexture(name,{width:512,height:512},scene,false),ctx=texture.getContext();ctx.fillStyle=base;ctx.fillRect(0,0,512,512);ctx.globalAlpha=.42;if(kind==="grain"){for(let i=0;i<180;i++){ctx.strokeStyle=i%3?accent:"#17100a";ctx.lineWidth=.5+Math.random()*2;const y=Math.random()*512;ctx.beginPath();ctx.moveTo(0,y);ctx.bezierCurveTo(130,y+Math.random()*18-9,370,y+Math.random()*18-9,512,y+Math.random()*10-5);ctx.stroke()}}else if(kind==="brushed"){for(let i=0;i<430;i++){ctx.strokeStyle=i%4?accent:"#ffffff";ctx.lineWidth=.25+Math.random();const y=Math.random()*512;ctx.beginPath();ctx.moveTo(Math.random()*110,y);ctx.lineTo(310+Math.random()*202,y+Math.random()*2);ctx.stroke()}}else{for(let i=0;i<1600;i++){ctx.fillStyle=i%5?accent:"#ffffff";const r=.4+Math.random()*2.2;ctx.fillRect(Math.random()*512,Math.random()*512,r,r)}}ctx.globalAlpha=1;texture.update(false);texture.wrapU=texture.wrapV=BABYLON.Texture.WRAP_ADDRESSMODE;texture.uScale=texture.vScale=scale;texture.anisotropicFilteringLevel=8;return texture;}
function applyTexture(mat,texture){mat.albedoTexture=texture;mat.useAmbientOcclusionFromMetallicTextureRed=false;return mat;}
const groundSurface=loadSurface("industrial-ground.jpg",10),asphaltSurface=groundSurface.clone();asphaltSurface.uScale=asphaltSurface.vScale=7;
const metalSurface=loadSurface("worn-gunmetal.jpg",4),weaponMetal=metalSurface.clone(),skinSurface=loadSurface("undead-skin.jpg",2.2),fabricSurface=loadSurface("tactical-fabric.jpg",3.5);
weaponMetal.uScale=weaponMetal.vScale=2.1;
applyTexture(mats.concrete,groundSurface);applyTexture(mats.asphalt,asphaltSurface);applyTexture(mats.wall,metalSurface);applyTexture(mats.dark,metalSurface.clone());applyTexture(mats.gun,weaponMetal);applyTexture(mats.gun2,fabricSurface.clone());applyTexture(mats.skin,skinSurface);applyTexture(mats.cloth,fabricSurface);applyTexture(mats.glove,fabricSurface.clone());
applyTexture(mats.orange,proceduralSurface("paint-wear","#a83220","#4b1712","speckle",4));applyTexture(mats.rubber,proceduralSurface("rubber-grain","#111312","#343834","speckle",5));applyTexture(mats.wood,proceduralSurface("wood-grain","#644b32","#a27c4d","grain",3));applyTexture(mats.blood,proceduralSurface("dried-blood","#4d100d","#a03628","speckle",2));applyTexture(mats.brass,proceduralSurface("brushed-brass","#8a6a32","#c19a55","brushed",3));applyTexture(mats.blade,proceduralSurface("brushed-steel","#9facb0","#e7edef","brushed",2));applyTexture(mats.cyan,proceduralSurface("signal-lens","#30727a","#8cf4f2","speckle",1));applyTexture(mats.glass,proceduralSurface("dirty-glass","#355963","#9fc0c2","speckle",2));
Object.values(mats).filter(mat=>mat.albedoTexture).forEach(mat=>mat.albedoColor=BABYLON.Color3.White());mats.dark.albedoColor.set(.62,.66,.68);mats.asphalt.albedoColor.set(.72,.74,.75);mats.gun2.albedoColor.set(.72,.78,.76);mats.glove.albedoColor.set(.5,.56,.58);

const hemi=new BABYLON.HemisphericLight("overcast",new BABYLON.Vector3(0,1,0),scene);hemi.intensity=.78;hemi.diffuse=new BABYLON.Color3(.56,.7,.78);hemi.groundColor=new BABYLON.Color3(.06,.075,.085);
const moon=new BABYLON.DirectionalLight("moon",new BABYLON.Vector3(-.4,-1,.32),scene);moon.position=new BABYLON.Vector3(55,90,-60);moon.intensity=2.15;moon.diffuse=new BABYLON.Color3(.64,.79,.94);
const shadows=new BABYLON.ShadowGenerator(innerWidth>900?2048:1024,moon);shadows.usePercentageCloserFiltering=true;shadows.filteringQuality=BABYLON.ShadowGenerator.QUALITY_MEDIUM;shadows.contactHardeningLightSizeUVRatio=.035;shadows.bias=.00025;shadows.normalBias=.018;
const imageFx=scene.imageProcessingConfiguration;imageFx.toneMappingEnabled=true;imageFx.toneMappingType=BABYLON.ImageProcessingConfiguration.TONEMAPPING_ACES;imageFx.exposure=.93;imageFx.contrast=1.22;imageFx.vignetteEnabled=true;imageFx.vignetteWeight=1.32;imageFx.vignetteStretch=.18;imageFx.vignetteColor=new BABYLON.Color4(.015,.02,.025,1);
const renderPipeline=new BABYLON.DefaultRenderingPipeline("field-grade",true,scene,[camera]);renderPipeline.fxaaEnabled=true;renderPipeline.samples=innerWidth>900?4:1;renderPipeline.bloomEnabled=true;renderPipeline.bloomThreshold=.88;renderPipeline.bloomWeight=.16;renderPipeline.bloomKernel=48;renderPipeline.sharpenEnabled=true;renderPipeline.sharpen.edgeAmount=.28;renderPipeline.sharpen.colorAmount=1;

function worldBox(name,p,s,mat=mats.wall,solid=true){const mesh=BABYLON.MeshBuilder.CreateBox(name,{width:s.x,height:s.y,depth:s.z},scene);mesh.position.copyFrom(p);mesh.material=mat;mesh.checkCollisions=solid;mesh.receiveShadows=true;mesh.metadata={solid};return mesh;}
function worldCylinder(name,p,height,diameter,mat=mats.wall,solid=true,tessellation=16){const mesh=BABYLON.MeshBuilder.CreateCylinder(name,{height,diameter,tessellation},scene);mesh.position.copyFrom(p);mesh.material=mat;mesh.checkCollisions=solid;mesh.receiveShadows=true;mesh.metadata={solid};return mesh;}
function localBox(name,parent,p,s,mat){const mesh=BABYLON.MeshBuilder.CreateBox(name,{width:s.x,height:s.y,depth:s.z},scene);mesh.parent=parent;mesh.position.copyFrom(p);mesh.material=mat;mesh.isPickable=false;return mesh;}
function localCylinder(name,parent,p,height,diameter,mat,rotation=new BABYLON.Vector3()){const mesh=BABYLON.MeshBuilder.CreateCylinder(name,{height,diameter,tessellation:16},scene);mesh.parent=parent;mesh.position.copyFrom(p);mesh.rotation.copyFrom(rotation);mesh.material=mat;mesh.isPickable=false;return mesh;}
function localTaper(name,parent,p,height,top,bottom,mat,rotation=new BABYLON.Vector3()){const mesh=BABYLON.MeshBuilder.CreateCylinder(name,{height,diameterTop:top,diameterBottom:bottom,tessellation:14,subdivisions:2},scene);mesh.parent=parent;mesh.position.copyFrom(p);mesh.rotation.copyFrom(rotation);mesh.material=mat;mesh.isPickable=false;return mesh;}

function makeSky(){const texture=new BABYLON.DynamicTexture("storm-sky",{width:1024,height:512},scene,false);const ctx=texture.getContext(),gradient=ctx.createLinearGradient(0,0,0,512);gradient.addColorStop(0,"#06101c");gradient.addColorStop(.48,"#17394c");gradient.addColorStop(1,"#875b48");ctx.fillStyle=gradient;ctx.fillRect(0,0,1024,512);for(let i=0;i<420;i++){const a=Math.random()*.78+.18;ctx.fillStyle=`rgba(215,232,238,${a})`;const r=Math.random()*1.3+.2;ctx.fillRect(Math.random()*1024,Math.random()*300,r,r)}for(let i=0;i<50;i++){ctx.fillStyle=`rgba(21,29,35,${.08+Math.random()*.18})`;ctx.beginPath();ctx.ellipse(Math.random()*1024,180+Math.random()*240,60+Math.random()*160,12+Math.random()*38,0,0,Math.PI*2);ctx.fill()}texture.update(false);const sky=BABYLON.MeshBuilder.CreateSphere("sky",{diameter:350,segments:24,sideOrientation:BABYLON.Mesh.BACKSIDE},scene),mat=new BABYLON.StandardMaterial("sky-material",scene);mat.diffuseTexture=texture;mat.emissiveTexture=texture;mat.disableLighting=true;mat.backFaceCulling=false;sky.material=mat;sky.isPickable=false;return sky;}

function createStreetLight(x,z,rotation=0){const root=new BABYLON.TransformNode("street-light",scene);root.position.set(x,0,z);root.rotation.y=rotation;const pole=localCylinder("lamp-pole",root,new BABYLON.Vector3(0,3.4,0),6.8,.14,mats.dark),arm=localBox("lamp-arm",root,new BABYLON.Vector3(.55,6.68,0),new BABYLON.Vector3(1.15,.1,.1),mats.dark),lamp=localBox("lamp-head",root,new BABYLON.Vector3(1.08,6.55,0),new BABYLON.Vector3(.48,.18,.3),mats.cyan);[pole,arm,lamp].forEach(m=>{m.isPickable=false;m.receiveShadows=true});const light=new BABYLON.PointLight("lamp-glow",new BABYLON.Vector3(x+Math.cos(rotation)*1.08,6.25,z-Math.sin(rotation)*1.08),scene);light.diffuse=new BABYLON.Color3(.43,.83,.88);light.intensity=1.25;light.range=18;}
function createVehicle(x,z,rotation=0,orange=false){const root=new BABYLON.TransformNode("wrecked-vehicle",scene);root.position.set(x,.75,z);root.rotation.y=rotation;const body=localBox("vehicle-body",root,new BABYLON.Vector3(0,0,0),new BABYLON.Vector3(4.8,1.1,2.15),orange?mats.orange:mats.wall),cabin=localBox("vehicle-cabin",root,new BABYLON.Vector3(.5,.85,0),new BABYLON.Vector3(2.25,.95,1.85),mats.dark),wind=localBox("broken-window",root,new BABYLON.Vector3(-.67,.93,0),new BABYLON.Vector3(.06,.62,1.55),mats.glass);[body,cabin,wind].forEach(m=>{m.checkCollisions=true;m.metadata={solid:true};m.receiveShadows=true});for(const sx of [-1.55,1.55])for(const sz of [-1,1]){const wheel=localCylinder("wheel",root,new BABYLON.Vector3(sx,-.35,sz),.35,.68,mats.rubber,new BABYLON.Vector3(Math.PI/2,0,0));wheel.receiveShadows=true}return root;}
function createBarricade(x,z,rotation=0){const root=new BABYLON.TransformNode("barricade",scene);root.position.set(x,0,z);root.rotation.y=rotation;for(let i=-1;i<=1;i++){const block=localBox("barrier-block",root,new BABYLON.Vector3(i*1.65,.62,0),new BABYLON.Vector3(1.5,1.25,.85),i===0?mats.orange:mats.concrete);block.checkCollisions=true;block.metadata={solid:true};block.receiveShadows=true}return root;}
function createContainer(x,z,rotation,colorMat=mats.wall){const c=worldBox("cargo-container",new BABYLON.Vector3(x,1.45,z),new BABYLON.Vector3(7.4,2.9,3),colorMat,true);c.rotation.y=rotation;for(let i=-2;i<=2;i++){const rib=worldBox("container-rib",new BABYLON.Vector3(x,1.45,z),new BABYLON.Vector3(.09,2.7,3.05),mats.dark,false);rib.rotation.y=rotation;const offset=new BABYLON.Vector3(i*1.35,0,0);offset.rotateByQuaternionToRef(BABYLON.Quaternion.FromEulerAngles(0,rotation,0),offset);rib.position.addInPlace(offset)}return c;}
function createWorld(){
  const ground=worldBox("kestrel-ground",new BABYLON.Vector3(0,-.32,12),new BABYLON.Vector3(190,.64,190),mats.concrete,true);ground.receiveShadows=true;makeSky();
  const road=worldBox("main-road",new BABYLON.Vector3(0,.015,12),new BABYLON.Vector3(18,.05,184),mats.asphalt,false);road.receiveShadows=true;for(let z=-75;z<90;z+=10)worldBox("road-mark",new BABYLON.Vector3(0,.052,z),new BABYLON.Vector3(.22,.025,4.8),mats.brass,false);
  [[0,4,-83,190,8,1],[0,4,107,190,8,1],[-95,4,12,1,8,190],[95,4,12,1,8,190]].forEach((v,i)=>worldBox(`perimeter-${i}`,new BABYLON.Vector3(v[0],v[1],v[2]),new BABYLON.Vector3(v[3],v[4],v[5]),mats.wall,true));
  const buildings=[[-57,5,-46,30,10,25],[-58,4,8,25,8,31],[-61,5,63,35,10,25],[56,5,-46,34,10,28],[61,4,8,24,8,32],[57,6,61,38,12,30],[-25,3,84,19,6,14],[27,4,86,24,8,16]];
  buildings.forEach((v,i)=>{const b=worldBox(`hangar-${i}`,new BABYLON.Vector3(v[0],v[1],v[2]),new BABYLON.Vector3(v[3],v[4],v[5]),i%2?mats.dark:mats.wall,true);if(i<6){const sign=worldBox(`hangar-sign-${i}`,new BABYLON.Vector3(v[0],v[1]+v[4]/2+.07,v[2]-v[5]/2-.04),new BABYLON.Vector3(Math.min(10,v[3]*.5),.18,.08),i%3?mats.cyan:mats.orange,false);sign.receiveShadows=false}});
  [[-28,-24,0],[25,-26,.12],[-29,35,-.08],[29,38,.05],[-18,66,.16],[19,63,-.12],[78,33,Math.PI/2],[-80,35,Math.PI/2]].forEach((p,i)=>createContainer(p[0],p[1],p[2],i%3===0?mats.orange:mats.wall));
  [[-22,-7,0],[20,16,.2],[-25,52,-.12],[25,76,.1],[-78,-5,Math.PI/2],[79,0,Math.PI/2]].forEach((p,i)=>createBarricade(p[0],p[1],p[2]));
  [[-18,-46,.12,false],[22,-4,-.08,true],[-30,77,.25,false],[31,48,-.18,false],[78,72,Math.PI/2,true]].forEach(p=>createVehicle(...p));
  for(let z=-68;z<=92;z+=28){createStreetLight(-12,z,0);createStreetLight(12,z,Math.PI)}
  for(let i=0;i<28;i++){const x=(i%2?-1:1)*(38+(i*13)%48),z=-68+(i*29)%160;const barrel=worldCylinder("fuel-barrel",new BABYLON.Vector3(x,.62,z),1.24,.78,i%5===0?mats.orange:mats.dark,true,20);barrel.rotation.z=(i%7===0)?Math.PI/2:0}
  for(let i=0;i<22;i++){const x=-84+(i*31)%168,z=-73+(i*43)%170;worldBox("supply-crate",new BABYLON.Vector3(x,.55,z),new BABYLON.Vector3(1.5,1.1,1.5),i%4?mats.wood:mats.wall,true)}
  for(let i=0;i<14;i++){const puddle=BABYLON.MeshBuilder.CreateCylinder("puddle",{height:.012,diameter:3+Math.random()*7,tessellation:28},scene);puddle.position.set(-80+Math.random()*160,.018,-70+Math.random()*170);puddle.scaling.z=.35+Math.random()*.4;puddle.material=mats.glass;puddle.isPickable=false}
  const tower=worldCylinder("watch-tower",new BABYLON.Vector3(82,8,-66),16,2.2,mats.dark,true,10);const platform=worldBox("tower-platform",new BABYLON.Vector3(82,14.5,-66),new BABYLON.Vector3(8,.7,8),mats.wall,true);shadows.addShadowCaster(tower);shadows.addShadowCaster(platform);
}
createWorld();

const viewRoot=new BABYLON.TransformNode("weapon-view",scene);viewRoot.parent=camera;viewRoot.position=new BABYLON.Vector3(.4,-.38,.88);viewRoot.rotation.y=Math.PI;const weaponRigs=[];
function addHands(root,leftPos,rightPos){const leftArm=localCylinder("left-forearm",root,leftPos,.48,.16,mats.cloth,new BABYLON.Vector3(Math.PI/2,0,0)),rightArm=localCylinder("right-forearm",root,rightPos,.5,.17,mats.cloth,new BABYLON.Vector3(Math.PI/2,0,0));const leftGlove=localBox("left-glove",root,leftPos.add(new BABYLON.Vector3(0,0,-.25)),new BABYLON.Vector3(.18,.15,.24),mats.glove),rightGlove=localBox("right-glove",root,rightPos.add(new BABYLON.Vector3(0,0,-.26)),new BABYLON.Vector3(.19,.16,.25),mats.glove);return[leftArm,rightArm,leftGlove,rightGlove]}
function createRifle(){const root=new BABYLON.TransformNode("rifle-rig",scene);root.parent=viewRoot;localBox("receiver",root,new BABYLON.Vector3(0,0,0),new BABYLON.Vector3(.18,.19,.78),mats.gun);localBox("upper",root,new BABYLON.Vector3(0,.1,-.08),new BABYLON.Vector3(.15,.09,.58),mats.gun2);localBox("stock",root,new BABYLON.Vector3(0,-.015,.55),new BABYLON.Vector3(.16,.2,.42),mats.gun2);localBox("handguard",root,new BABYLON.Vector3(0,.015,-.55),new BABYLON.Vector3(.17,.17,.55),mats.gun2);localCylinder("barrel",root,new BABYLON.Vector3(0,.02,-1),.55,.045,mats.gun,new BABYLON.Vector3(Math.PI/2,0,0));localCylinder("suppressor",root,new BABYLON.Vector3(0,.02,-1.3),.34,.085,mats.gun,new BABYLON.Vector3(Math.PI/2,0,0));const mag=localBox("magazine",root,new BABYLON.Vector3(0,-.2,.08),new BABYLON.Vector3(.13,.34,.2),mats.gun2);mag.rotation.x=-.16;localBox("rail",root,new BABYLON.Vector3(0,.17,-.22),new BABYLON.Vector3(.12,.035,.72),mats.gun);localBox("optic",root,new BABYLON.Vector3(0,.25,-.05),new BABYLON.Vector3(.14,.14,.22),mats.gun2);const lens=localCylinder("optic-lens",root,new BABYLON.Vector3(0,.25,-.17),.02,.09,mats.cyan,new BABYLON.Vector3(Math.PI/2,0,0));localBox("charging-handle",root,new BABYLON.Vector3(.14,.08,.12),new BABYLON.Vector3(.13,.045,.07),mats.gun);addHands(root,new BABYLON.Vector3(-.18,-.16,-.42),new BABYLON.Vector3(.16,-.2,.26));const muzzle=BABYLON.MeshBuilder.CreateSphere("rifle-flash",{diameter:.14,segments:6},scene);muzzle.parent=root;muzzle.position.z=-1.5;muzzle.material=mats.orange;muzzle.isPickable=false;muzzle.isVisible=false;root.metadata={muzzle};return root}
function createPistol(){const root=new BABYLON.TransformNode("pistol-rig",scene);root.parent=viewRoot;localBox("pistol-slide",root,new BABYLON.Vector3(0,.05,-.25),new BABYLON.Vector3(.16,.16,.66),mats.gun);const frame=localBox("pistol-frame",root,new BABYLON.Vector3(0,-.07,-.12),new BABYLON.Vector3(.14,.14,.42),mats.gun2),grip=localBox("pistol-grip",root,new BABYLON.Vector3(0,-.3,.02),new BABYLON.Vector3(.15,.45,.2),mats.gun2);grip.rotation.x=-.2;localCylinder("pistol-barrel",root,new BABYLON.Vector3(0,.055,-.64),.22,.04,mats.gun,new BABYLON.Vector3(Math.PI/2,0,0));localBox("front-sight",root,new BABYLON.Vector3(0,.15,-.48),new BABYLON.Vector3(.035,.055,.04),mats.cyan);addHands(root,new BABYLON.Vector3(-.13,-.31,.05),new BABYLON.Vector3(.12,-.27,.08));const muzzle=BABYLON.MeshBuilder.CreateSphere("pistol-flash",{diameter:.12,segments:6},scene);muzzle.parent=root;muzzle.position.set(0,.055,-.77);muzzle.material=mats.orange;muzzle.isPickable=false;muzzle.isVisible=false;root.metadata={muzzle,slide:frame};return root}
function createKnife(){const root=new BABYLON.TransformNode("knife-rig",scene);root.parent=viewRoot;const handle=localCylinder("knife-handle",root,new BABYLON.Vector3(0,-.02,.12),.5,.12,mats.glove,new BABYLON.Vector3(Math.PI/2,0,0));localBox("knife-guard",root,new BABYLON.Vector3(0,.0,-.17),new BABYLON.Vector3(.3,.06,.08),mats.gun);const blade=localBox("knife-blade",root,new BABYLON.Vector3(0,.02,-.55),new BABYLON.Vector3(.09,.035,.75),mats.blade);blade.rotation.z=.03;const tip=BABYLON.MeshBuilder.CreateCylinder("knife-tip",{height:.22,diameterTop:0,diameterBottom:.1,tessellation:4},scene);tip.parent=root;tip.position.set(0,.02,-.99);tip.rotation.x=Math.PI/2;tip.material=mats.blade;tip.isPickable=false;addHands(root,new BABYLON.Vector3(-.3,-.29,.22),new BABYLON.Vector3(.09,-.12,.19));root.rotation.z=-.28;root.metadata={};return root}
weaponRigs.push(createRifle(),createPistol(),createKnife());
function detailWeaponRigs(){const rifle=weaponRigs[0],pistol=weaponRigs[1],knife=weaponRigs[2];for(let i=-3;i<=3;i++)localBox("rail-notch",rifle,new BABYLON.Vector3(0,.194,-.22+i*.085),new BABYLON.Vector3(.155,.018,.035),mats.gun);for(let i=-2;i<=2;i++){localBox("handguard-vent",rifle,new BABYLON.Vector3(.091,.02,-.55+i*.09),new BABYLON.Vector3(.012,.055,.045),mats.dark);localBox("grip-rib",pistol,new BABYLON.Vector3(0,-.3+i*.055,.126),new BABYLON.Vector3(.154,.014,.012),mats.rubber)}localCylinder("selector",rifle,new BABYLON.Vector3(.102,.03,.02),.018,.055,mats.brass,new BABYLON.Vector3(0,0,Math.PI/2));localCylinder("slide-pin",pistol,new BABYLON.Vector3(.088,-.06,-.08),.018,.045,mats.brass,new BABYLON.Vector3(0,0,Math.PI/2));for(let i=-2;i<=2;i++)localBox("slide-serration",pistol,new BABYLON.Vector3(.086,.065,.01+i*.026),new BABYLON.Vector3(.012,.11,.011),mats.dark);localBox("blade-fuller",knife,new BABYLON.Vector3(0,.041,-.58),new BABYLON.Vector3(.035,.006,.5),mats.gun)}
detailWeaponRigs();weaponRigs.forEach((rig,i)=>rig.setEnabled(i===0));

function selectWeapon(index){if(index<0||index>=LOADOUT.length||index===state.currentSlot||state.reloading)return;state.currentSlot=index;state.firing=false;state.switchTimer=.38;weaponRigs.forEach((rig,i)=>rig.setEnabled(i===index));document.querySelectorAll(".loadout-strip span").forEach((slot,i)=>slot.classList.toggle("active",i===index));updateHud();tone(170+index*80,.05,"square",.018)}
function currentWeapon(){return LOADOUT[state.currentSlot]}

const spawnPoints=[[-87,0,-73],[87,0,-68],[-88,0,-15],[88,0,-10],[-88,0,47],[88,0,50],[-70,0,98],[70,0,98],[0,0,102]];
function chooseZombieType(){const weights=WAVES[Math.max(0,state.waveIndex)].weights,r=Math.random();return r<weights[0]?"walker":r<weights[0]+weights[1]?"runner":"brute"}
function createZombie(typeName,position){const type=ZOMBIE_TYPES[typeName],root=new BABYLON.TransformNode(`zombie-${typeName}`,scene);root.position.copyFrom(position);root.scaling.setAll(type.scale);const bodyMat=applyTexture(makeMat(`zombie-cloth-${Math.random()}`,type.color,{rough:.98}),fabricSurface.clone()),skinMat=typeName==="brute"?applyTexture(makeMat(`brute-skin-${Math.random()}`,"#625b4d",{rough:.93}),skinSurface.clone()):mats.skin;
  bodyMat.albedoColor=BABYLON.Color3.FromHexString(type.color).scale(1.7);if(typeName==="brute")skinMat.albedoColor.set(.72,.67,.57);
  const body=localTaper("zombie-torso",root,new BABYLON.Vector3(0,1.28,0),1.04,.58,.72,bodyMat),vest=localTaper("torn-vest",root,new BABYLON.Vector3(0,1.34,-.01),.7,.64,.7,mats.cloth),head=BABYLON.MeshBuilder.CreateSphere("zombie-head",{diameter:.49,segments:18},scene);head.parent=root;head.position.set(0,2.04,-.03);head.scaling.set(.92,1.08,.9);head.material=skinMat;
  const jaw=localTaper("zombie-jaw",root,new BABYLON.Vector3(0,1.9,-.19),.22,.25,.34,skinMat,new BABYLON.Vector3(Math.PI/2,0,0)),nose=localTaper("broken-nose",root,new BABYLON.Vector3(0,2.05,-.25),.16,.02,.09,skinMat,new BABYLON.Vector3(Math.PI/2,0,0)),eyeL=BABYLON.MeshBuilder.CreateSphere("zombie-eye",{diameter:.052,segments:8},scene),eyeR=eyeL.clone("zombie-eye");eyeL.parent=root;eyeR.parent=root;eyeL.position.set(-.105,2.09,-.232);eyeR.position.set(.105,2.09,-.232);eyeL.material=eyeR.material=mats.orange;
  const armL=localTaper("zombie-arm",root,new BABYLON.Vector3(-.47,1.28,-.17),.98,.15,.23,skinMat,new BABYLON.Vector3(Math.PI/2.35,0,.13)),armR=localTaper("zombie-arm",root,new BABYLON.Vector3(.47,1.28,-.17),.98,.15,.23,skinMat,new BABYLON.Vector3(Math.PI/2.35,0,-.13)),legL=localTaper("zombie-leg",root,new BABYLON.Vector3(-.2,.48,0),.92,.18,.28,bodyMat),legR=localTaper("zombie-leg",root,new BABYLON.Vector3(.2,.48,0),.92,.18,.28,bodyMat),bootL=localBox("zombie-boot",root,new BABYLON.Vector3(-.2,.08,-.09),new BABYLON.Vector3(.28,.2,.43),mats.rubber),bootR=localBox("zombie-boot",root,new BABYLON.Vector3(.2,.08,-.09),new BABYLON.Vector3(.28,.2,.43),mats.rubber),belt=localCylinder("zombie-belt",root,new BABYLON.Vector3(0,.91,0),.13,.62,mats.glove),wound=localBox("zombie-wound",root,new BABYLON.Vector3(.18,1.38,-.31),new BABYLON.Vector3(.2,.25,.025),mats.blood);
  const meshes=[body,vest,head,jaw,nose,eyeL,eyeR,armL,armR,legL,legR,bootL,bootR,belt,wound],zombie={type:typeName,root,meshes,armL,armR,legL,legR,health:type.health*(1+state.waveIndex*.08),speed:type.speed*(1+state.waveIndex*.035),damage:type.damage,attackTimer:.4+Math.random(),voiceTimer:1.2+Math.random()*4,phase:Math.random()*6,stagger:0,dead:false};meshes.forEach(mesh=>{mesh.metadata={zombie,headshot:mesh===head||mesh===jaw||mesh===nose};mesh.isPickable=true;shadows.addShadowCaster(mesh)});state.enemies.push(zombie);return zombie}
function spawnZombie(){const choices=spawnPoints.map(p=>new BABYLON.Vector3(...p)).filter(p=>BABYLON.Vector3.DistanceSquared(p,camera.position)>625),position=choices[Math.floor(Math.random()*choices.length)]||new BABYLON.Vector3(80,0,80);createZombie(chooseZombieType(),position)}

function addFeed(text,color="#edf0e8"){const row=document.createElement("p");row.textContent=text;row.style.borderColor=color;feed.prepend(row);setTimeout(()=>row.remove(),3100)}
function showWaveBanner(title,text,color="#ff5b35"){waveBannerTitle.textContent=title;waveBannerText.textContent=text;waveBannerTitle.style.color=color;waveBanner.classList.add("show");setTimeout(()=>waveBanner.classList.remove("show"),2600)}
function initAudio(){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return null;if(!state.ac){const ac=state.ac=new AC(),master=state.audioMaster=ac.createGain(),compressor=ac.createDynamicsCompressor();master.gain.value=.72;compressor.threshold.value=-13;compressor.knee.value=16;compressor.ratio.value=5;compressor.attack.value=.003;compressor.release.value=.22;master.connect(compressor);compressor.connect(ac.destination);const buffer=state.noiseBuffer=ac.createBuffer(1,ac.sampleRate*2,ac.sampleRate),data=buffer.getChannelData(0);let brown=0;for(let i=0;i<data.length;i++){const white=Math.random()*2-1;brown=(brown+.025*white)/1.025;data[i]=white*.7+brown*1.7}const wind=ac.createBufferSource(),windFilter=ac.createBiquadFilter(),windGain=ac.createGain(),lfo=ac.createOscillator(),lfoGain=ac.createGain();wind.buffer=buffer;wind.loop=true;windFilter.type="lowpass";windFilter.frequency.value=680;windGain.gain.value=.035;lfo.frequency.value=.11;lfoGain.gain.value=.014;lfo.connect(lfoGain);lfoGain.connect(windGain.gain);wind.connect(windFilter);windFilter.connect(windGain);windGain.connect(master);wind.start();lfo.start();const hum=ac.createOscillator(),humGain=ac.createGain();hum.type="sine";hum.frequency.value=43;humGain.gain.value=.012;hum.connect(humGain);humGain.connect(master);hum.start();state.ambientNodes=[wind,lfo,hum]}if(state.ac.state==="suspended")state.ac.resume();return state.ac}
function audioBus(position){if(!state.ac||!position)return state.audioMaster;const panner=state.ac.createPanner();panner.panningModel="HRTF";panner.distanceModel="inverse";panner.refDistance=2;panner.maxDistance=75;panner.rolloffFactor=1.25;if(panner.positionX){panner.positionX.value=position.x;panner.positionY.value=position.y;panner.positionZ.value=position.z}else panner.setPosition(position.x,position.y,position.z);panner.connect(state.audioMaster);return panner}
function noiseBurst(duration=.1,volume=.1,low=7000,high=45,position=null,delay=0){const ac=initAudio();if(!ac)return;const source=ac.createBufferSource(),lowpass=ac.createBiquadFilter(),highpass=ac.createBiquadFilter(),gain=ac.createGain(),start=ac.currentTime+delay;source.buffer=state.noiseBuffer;lowpass.type="lowpass";lowpass.frequency.value=low;highpass.type="highpass";highpass.frequency.value=high;gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(volume,start+.003);gain.gain.exponentialRampToValueAtTime(.0001,start+duration);source.connect(lowpass);lowpass.connect(highpass);highpass.connect(gain);gain.connect(audioBus(position));source.start(start,Math.random());source.stop(start+duration+.03)}
function synth(freq,duration,type="triangle",volume=.025,position=null,delay=0,endFreq=null){const ac=initAudio();if(!ac)return;const osc=ac.createOscillator(),gain=ac.createGain(),start=ac.currentTime+delay;osc.type=type;osc.frequency.setValueAtTime(freq,start);if(endFreq)osc.frequency.exponentialRampToValueAtTime(Math.max(1,endFreq),start+duration);gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(volume,start+.004);gain.gain.exponentialRampToValueAtTime(.0001,start+duration);osc.connect(gain);gain.connect(audioBus(position));osc.start(start);osc.stop(start+duration+.02)}
function tone(freq,duration,type="triangle",volume=.025){synth(freq,duration,type,volume)}
function playGunSound(kind){if(kind==="pistol"){noiseBurst(.16,.22,8200,90);synth(145,.13,"triangle",.13,null,0,62);noiseBurst(.035,.075,5200,900,null,.045)}else{noiseBurst(.13,.19,7600,70);synth(92,.16,"triangle",.14,null,0,42);noiseBurst(.032,.06,4800,1100,null,.032);noiseBurst(.09,.045,1800,120,null,.075)}}
function playKnifeSound(hit=false,position=null){noiseBurst(.18,hit?.12:.07,hit?2100:4800,hit?80:650,position);synth(hit?76:190,hit?.15:.09,hit?"triangle":"sawtooth",hit?.065:.022,position,0,hit?42:110)}
function playZombieVoice(zombie,death=false){const p=zombie.root.position,base=zombie.type==="brute"?48:zombie.type==="runner"?76:61;noiseBurst(death?.55:.72,death?.1:.045,death?1200:1650,45,p);synth(base,death?.62:.74,"sawtooth",death?.055:.026,p,0,death?25:base*.72);synth(base*1.46,death?.4:.56,"triangle",death?.027:.014,p,.035,death?34:base*.9)}
function playImpact(position,headshot=false){noiseBurst(.09,headshot?.095:.06,headshot?3600:2100,100,position);synth(headshot?132:78,.11,"triangle",headshot?.045:.032,position,0,42)}
function updateAudioListener(){if(!state.ac)return;const listener=state.ac.listener,forward=camera.getForwardRay().direction,up=camera.upVector;if(listener.positionX){listener.positionX.value=camera.position.x;listener.positionY.value=camera.position.y;listener.positionZ.value=camera.position.z;listener.forwardX.value=forward.x;listener.forwardY.value=forward.y;listener.forwardZ.value=forward.z;listener.upX.value=up.x;listener.upY.value=up.y;listener.upZ.value=up.z}else{listener.setPosition(camera.position.x,camera.position.y,camera.position.z);listener.setOrientation(forward.x,forward.y,forward.z,up.x,up.y,up.z)}}
function showHit(headshot=false){hitMarker.classList.add("show");hitMarker.style.filter=headshot?"drop-shadow(0 0 5px #ff5b35)":"";setTimeout(()=>hitMarker.classList.remove("show"),90)}

function updateHud(){const weapon=currentWeapon();labels.healthValue.textContent=Math.ceil(state.health);labels.healthBar.style.width=`${state.health}%`;labels.armorValue.textContent=Math.ceil(state.armor);labels.armorBar.style.width=`${state.armor}%`;labels.playerLevel.textContent=state.level;labels.ammoCurrent.textContent=weapon.kind==="knife"?"—":weapon.ammo;labels.ammoReserve.textContent=weapon.kind==="knife"?"∞":weapon.reserve;labels.weaponName.textContent=weapon.name;labels.weaponRarity.textContent=weapon.rarity;labels.weaponRarity.style.color=weapon.color;document.querySelector(".weapon-panel>p").textContent=weapon.mode;labels.killCount.textContent=state.waveKills;labels.killTarget.textContent=state.waveTarget;labels.objectiveProgress.style.width=`${state.waveTarget?Math.min(100,state.waveKills/state.waveTarget*100):0}%`;labels.xpLabel.textContent=`${state.xp} / ${state.xpNeeded} XP`;labels.xpBar.style.width=`${state.xp/state.xpNeeded*100}%`}
function gainXp(amount){state.xp+=amount;while(state.xp>=state.xpNeeded){state.xp-=state.xpNeeded;state.level++;state.xpNeeded=Math.round(state.xpNeeded*1.3);state.health=Math.min(100,state.health+28);state.armor=Math.min(100,state.armor+22);addFeed(`SEVİYE ${state.level} · CAN VE ZIRH YENİLENDİ`,"#66e3ee")}updateHud()}

function beginWave(index){const wave=WAVES[index];state.waveIndex=index;state.waveKills=0;state.waveTarget=wave.count;state.spawnRemaining=wave.count;state.spawnTimer=.45;state.waveActive=true;state.intermission=0;labels.objectiveTitle.textContent=`DALGA ${index+1} / ${WAVES.length} · ${wave.label}`;labels.objectiveText.innerHTML=`<b id="kill-count">0</b> / <span id="kill-target">${wave.count}</span> zombi etkisiz`;labels.killCount=$("kill-count");labels.killTarget=$("kill-target");showWaveBanner(`DALGA ${index+1}`,wave.label);addFeed(`DALGA ${index+1} BAŞLADI`,"#ff5b35");synth(62,.55,"sawtooth",.045,null,0,42);synth(94,.38,"triangle",.03,null,.12,55);updateHud()}
function finishWave(){state.waveActive=false;if(state.waveIndex>=WAVES.length-1){activateExtraction();return}state.intermission=7;labels.objectiveTitle.textContent=`DALGA ${state.waveIndex+1} TAMAMLANDI`;showWaveBanner("BÖLGE TEMİZ",`DALGA ${state.waveIndex+2} HAZIRLANIYOR`,"#66e3ee");state.health=Math.min(100,state.health+18);state.armor=Math.min(100,state.armor+15);LOADOUT.forEach(w=>{if(w.kind!=="knife")w.reserve=Math.min(w.kind==="rifle"?210:105,w.reserve+Math.ceil(w.mag*.7))});updateHud()}

function spawnLoot(position){const roll=Math.random(),type=roll>.68?"armor":roll>.28?"ammo":"supply",color=type==="armor"?"#6a9dff":type==="supply"?"#ffcb57":"#edf0e8",mesh=BABYLON.MeshBuilder.CreateBox("loot",{size:.5},scene);mesh.position.copyFrom(position);mesh.position.y=.48;mesh.rotation.z=Math.PI/4;mesh.material=makeMat(`loot-${Math.random()}`,color,{metal:.35,rough:.3,emissive:.55});mesh.isPickable=false;const light=new BABYLON.PointLight("loot-glow",mesh.position.clone(),scene);light.diffuse=BABYLON.Color3.FromHexString(color);light.intensity=.7;light.range=4;state.loot.push({mesh,light,type,color,baseY:.48,phase:Math.random()*6})}
function pickupLoot(loot){if(loot.type==="armor"){state.armor=Math.min(100,state.armor+35);addFeed("ZIRH PLAKASI +35",loot.color)}else if(loot.type==="supply"){state.health=Math.min(100,state.health+30);LOADOUT[0].reserve=Math.min(210,LOADOUT[0].reserve+45);LOADOUT[1].reserve=Math.min(105,LOADOUT[1].reserve+24);addFeed("SAHA ÇANTASI · CAN + MÜHİMMAT",loot.color)}else{LOADOUT[0].reserve=Math.min(210,LOADOUT[0].reserve+42);LOADOUT[1].reserve=Math.min(105,LOADOUT[1].reserve+21);addFeed("MÜHİMMAT ALINDI",loot.color)}gainXp(8);loot.mesh.dispose();loot.light.dispose();state.loot=state.loot.filter(item=>item!==loot);updateHud()}

function killZombie(zombie,headshot){if(zombie.dead)return;zombie.dead=true;playZombieVoice(zombie,true);state.totalKills++;state.waveKills++;gainXp(headshot?40:zombie.type==="brute"?55:25);addFeed(headshot?"KAFA ATIŞI · +40 XP":zombie.type==="brute"?"İRİ ZOMBİ DÜŞTÜ · +55 XP":"ZOMBİ ETKİSİZ · +25 XP",headshot?"#ff5b35":"#edf0e8");if(Math.random()<.56)spawnLoot(zombie.root.position.clone());zombie.meshes.forEach(mesh=>mesh.dispose());zombie.root.dispose();state.enemies=state.enemies.filter(item=>item!==zombie);updateHud();if(state.waveActive&&state.spawnRemaining===0&&state.enemies.length===0)finishWave()}

function shoot(){const weapon=currentWeapon();if(!state.running||state.paused||state.ended||state.reloading||state.switchTimer>0)return;const now=performance.now()/1000;if(now-state.lastShot<1/weapon.fireRate)return;state.lastShot=now;if(weapon.kind==="knife"){state.meleeTimer=.46;state.recoil=.25;playKnifeSound(false);const ray=camera.getForwardRay(weapon.range),pick=scene.pickWithRay(ray,m=>Boolean(m.metadata?.zombie&&!m.metadata.zombie.dead));if(pick?.hit){const zombie=pick.pickedMesh.metadata.zombie;zombie.health-=weapon.damage;zombie.stagger=.35;showHit(false);playKnifeSound(true,zombie.root.position);if(zombie.health<=0)killZombie(zombie,false)}return}if(weapon.ammo<=0){reload();return}weapon.ammo--;state.recoil=weapon.kind==="pistol"?.2:.12;camera.rotation.x-=weapon.kind==="pistol"?.014:.007+Math.random()*.005;const muzzle=weaponRigs[state.currentSlot].metadata.muzzle;muzzle.isVisible=true;setTimeout(()=>muzzle.isVisible=false,38);playGunSound(weapon.kind);const ray=camera.getForwardRay(weapon.range);ray.direction.x+=(Math.random()-.5)*weapon.spread;ray.direction.y+=(Math.random()-.5)*weapon.spread;const pick=scene.pickWithRay(ray,m=>Boolean(m.metadata?.zombie&&!m.metadata.zombie.dead));if(pick?.hit){const zombie=pick.pickedMesh.metadata.zombie,headshot=pick.pickedMesh.metadata.headshot;zombie.health-=weapon.damage*(headshot?1.72:1);zombie.stagger=.12;showHit(headshot);playImpact(pick.pickedPoint||zombie.root.position,headshot);if(zombie.health<=0)killZombie(zombie,headshot)}updateHud()}
function reload(){const weapon=currentWeapon();if(weapon.kind==="knife"||state.reloading||weapon.ammo>=weapon.mag||weapon.reserve<=0||state.ended)return;state.reloading=true;state.reloadTimer=weapon.kind==="pistol"?1.15:1.65;reloadIndicator.classList.remove("show");void reloadIndicator.offsetWidth;reloadIndicator.classList.add("show");noiseBurst(.045,.035,5200,800);synth(190,.045,"square",.018,null,.12,145)}
function finishReload(){const weapon=currentWeapon(),needed=weapon.mag-weapon.ammo,taken=Math.min(needed,weapon.reserve);weapon.ammo+=taken;weapon.reserve-=taken;state.reloading=false;reloadIndicator.classList.remove("show");noiseBurst(.05,.04,6200,950);synth(410,.055,"square",.018,null,0,280);updateHud()}
function damagePlayer(amount){if(state.ended)return;let remaining=amount;if(state.armor>0){const absorbed=Math.min(state.armor,remaining);state.armor-=absorbed;remaining-=absorbed}state.health=Math.max(0,state.health-remaining);damageVignette.classList.add("show");state.damageFlashTimer=.24;noiseBurst(.18,.08,1200,55);synth(58,.22,"sawtooth",.035,null,0,35);updateHud();if(state.health<=0)endGame(false)}

function activateExtraction(){if(state.extraction)return;labels.objectiveTitle.textContent="BEŞ DALGA TAMAMLANDI";labels.objectiveText.innerHTML="Kuzey kapısındaki <b>tahliye işaretine</b> ulaş";labels.objectiveProgress.style.width="100%";const zone=BABYLON.MeshBuilder.CreateCylinder("extraction",{height:.08,diameter:9,tessellation:36},scene);zone.position.set(0,.05,100);zone.material=makeMat("extraction-signal","#66e3ee",{metal:.1,rough:.25,emissive:.7,alpha:.34});zone.isPickable=false;const beacon=new BABYLON.PointLight("extraction-beacon",new BABYLON.Vector3(0,2,100),scene);beacon.diffuse=BABYLON.Color3.FromHexString("#66e3ee");beacon.intensity=2.3;beacon.range=20;state.extraction={zone,beacon};showWaveBanner("TAHLİYE AÇIK","KUZEY KAPISINA ULAŞ","#66e3ee");addFeed("TAHLİYE İŞARETİ AKTİF","#66e3ee")}

function updateZombies(dt){for(const z of state.enemies){if(z.dead)continue;z.attackTimer-=dt;z.voiceTimer-=dt;z.stagger=Math.max(0,z.stagger-dt);z.phase+=dt*(4+z.speed);let dir=camera.position.subtract(z.root.position);dir.y=0;const distance=dir.length();if(z.voiceTimer<=0&&distance<48){playZombieVoice(z,false);z.voiceTimer=3.5+Math.random()*6}if(distance>1.55&&z.stagger<=0){dir.normalize();const obstacle=scene.pickWithRay(new BABYLON.Ray(z.root.position.add(new BABYLON.Vector3(0,.8,0)),dir,1.3),m=>Boolean(m.metadata?.solid));if(obstacle?.hit)dir=new BABYLON.Vector3(-dir.z,0,dir.x*(Math.random()>.5?1:-1)).normalize();z.root.position.addInPlace(dir.scale(z.speed*dt))}z.root.rotation.y=Math.atan2(-dir.x,-dir.z);const swing=Math.sin(z.phase)*.48;z.armL.rotation.x=1.25+swing*.35;z.armR.rotation.x=1.25-swing*.35;z.legL.rotation.x=swing*.32;z.legR.rotation.x=-swing*.32;z.root.position.y=Math.abs(Math.sin(z.phase))*0.025;if(distance<1.9&&z.attackTimer<=0){z.attackTimer=.82+Math.random()*.45;damagePlayer(z.damage)}}}
function updateLoot(dt){let nearest=null,nearestDistance=Infinity;for(const loot of state.loot){loot.phase+=dt*2.2;loot.mesh.rotation.y+=dt*1.5;loot.mesh.position.y=loot.baseY+Math.sin(loot.phase)*.12;loot.light.position.copyFrom(loot.mesh.position);const d=BABYLON.Vector3.Distance(camera.position,loot.mesh.position);if(d<nearestDistance){nearest=loot;nearestDistance=d}}if(nearest&&nearestDistance<3.2){const name=nearest.type==="armor"?"ZIRH PLAKASI":nearest.type==="supply"?"SAHA ÇANTASI":"MÜHİMMAT";interaction.innerHTML=`<b>[E]</b> ${name} AL`;interaction.classList.add("show");state.nearestLoot=nearest}else{interaction.classList.remove("show");state.nearestLoot=null}}
function updateViewModel(dt){const rig=weaponRigs[state.currentSlot],weapon=currentWeapon(),moving=camera.cameraDirection.length()>.004,bob=moving?Math.sin(state.elapsed*(keys.shift?14:10))*.014:0,sway=moving?Math.cos(state.elapsed*(keys.shift?7:5))*.012:0,sprint=keys.shift&&moving?1:0;state.recoil=Math.max(0,state.recoil-dt*4.8);state.switchTimer=Math.max(0,state.switchTimer-dt);const base=weapon.kind==="rifle"?new BABYLON.Vector3(.41,-.37,.91):weapon.kind==="pistol"?new BABYLON.Vector3(.48,-.39,.78):new BABYLON.Vector3(.51,-.36,.67);let reloadArc=0;if(state.reloading){state.reloadTimer-=dt;const duration=weapon.kind==="pistol"?1.15:1.65,phase=1-state.reloadTimer/duration;reloadArc=Math.sin(phase*Math.PI);if(state.reloadTimer<=0)finishReload()}if(state.meleeTimer>0)state.meleeTimer=Math.max(0,state.meleeTimer-dt);const meleePhase=state.meleeTimer>0?Math.sin((1-state.meleeTimer/.46)*Math.PI):0;viewRoot.position.x+=(base.x+sway-viewRoot.position.x)*Math.min(1,dt*14);viewRoot.position.y+=(base.y+Math.abs(bob)-reloadArc*.22-sprint*.13-viewRoot.position.y)*Math.min(1,dt*14);viewRoot.position.z+=(base.z+bob+state.recoil*.22+sprint*.08-viewRoot.position.z)*Math.min(1,dt*18);viewRoot.rotation.z+=(sway*.8+reloadArc*.55+(weapon.kind==="knife"?-meleePhase*1.15:0)-viewRoot.rotation.z)*Math.min(1,dt*16);viewRoot.rotation.x+=(sprint*.28+(weapon.kind==="knife"?meleePhase*.8:0)-viewRoot.rotation.x)*Math.min(1,dt*16);rig.rotation.y=weapon.kind==="knife"?meleePhase*.7:0}
function updateCompass(){const deg=(camera.rotation.y*180/Math.PI%360+360)%360,points=["N","NE","E","SE","S","SW","W","NW"];labels.heading.textContent=`${points[Math.round(deg/45)%8]} · ${String(Math.round(deg)).padStart(3,"0")}`}

function updateGame(dt){if(!state.running||state.paused||state.ended)return;state.elapsed+=dt;updateAudioListener();const weapon=currentWeapon();camera.speed=weapon.speed*(keys.shift?1.42:1);if(state.firing&&weapon.auto)shoot();updateViewModel(dt);updateZombies(dt);updateLoot(dt);updateCompass();if(state.waveActive&&state.spawnRemaining>0){state.spawnTimer-=dt;if(state.spawnTimer<=0&&state.enemies.length<10){spawnZombie();state.spawnRemaining--;state.spawnTimer=Math.max(.3,.82-state.waveIndex*.1)}}if(!state.waveActive&&state.intermission>0){state.intermission-=dt;labels.objectiveText.innerHTML=`Sonraki dalga <b>${Math.max(0,Math.ceil(state.intermission))}</b> saniye`;if(state.intermission<=0)beginWave(state.waveIndex+1)}if(state.extraction){state.extraction.zone.rotation.y+=dt*.25;state.extraction.beacon.intensity=1.8+Math.sin(state.elapsed*4)*.65;if(BABYLON.Vector3.Distance(camera.position,state.extraction.zone.position)<4.2)endGame(true)}if(state.damageFlashTimer>0){state.damageFlashTimer-=dt;if(state.damageFlashTimer<=0)damageVignette.classList.remove("show")}}
function endGame(success){if(state.ended)return;state.ended=true;state.running=false;state.firing=false;document.exitPointerLock?.();hud.classList.remove("active");hud.setAttribute("aria-hidden","true");resultScreen.hidden=false;labels.resultTitle.textContent=success?"TAHLİYE BAŞARILI":"OPERATÖR DÜŞTÜ";labels.resultTitle.style.color=success?"#66e3ee":"#ff5b35";labels.resultText.textContent=success?`Beş dalga ve ${state.totalKills} zombi ${Math.floor(state.elapsed/60)}:${String(Math.floor(state.elapsed%60)).padStart(2,"0")} sürede temizlendi. Kestrel-7 yeniden kontrol altında.`:`Dalga ${state.waveIndex+1} sırasında operatör düştü. Silah hızlarını kullan, mesafeyi koru ve yeniden dene.`;labels.resultKills.textContent=state.totalKills;labels.resultLevel.textContent=state.level;labels.resultWeapon.textContent=currentWeapon().name}
async function enterFullscreen(){const target=document.documentElement,request=target.requestFullscreen||target.webkitRequestFullscreen;if(request&&!document.fullscreenElement){try{await request.call(target);await screen.orientation?.lock?.("landscape")}catch{}}}
async function startGame(){initAudio();await enterFullscreen();bootScreen.classList.add("hidden");resultScreen.hidden=true;hud.classList.add("active");hud.setAttribute("aria-hidden","false");state.running=true;state.paused=false;state.ended=false;canvas.focus();canvas.requestPointerLock?.();if(state.waveIndex<0)beginWave(0);updateHud();addFeed("KESTREL SAVUNMASI BAŞLADI","#66e3ee")}

window.addEventListener("keydown",e=>{if(e.code==="ShiftLeft"||e.code==="ShiftRight")keys.shift=true;if(e.code==="Digit1")selectWeapon(0);if(e.code==="Digit2")selectWeapon(1);if(e.code==="Digit3")selectWeapon(2);if(e.code==="KeyR"){e.preventDefault();reload()}if(e.code==="KeyE"&&state.nearestLoot){e.preventDefault();pickupLoot(state.nearestLoot)}});
window.addEventListener("keyup",e=>{if(e.code==="ShiftLeft"||e.code==="ShiftRight")keys.shift=false});
window.addEventListener("wheel",e=>{if(!state.running)return;selectWeapon((state.currentSlot+(e.deltaY>0?1:-1)+LOADOUT.length)%LOADOUT.length)},{passive:true});
window.addEventListener("mousedown",e=>{if(e.button===0&&document.pointerLockElement===canvas){state.firing=true;shoot()}});window.addEventListener("mouseup",e=>{if(e.button===0)state.firing=false});window.addEventListener("blur",()=>{state.firing=false;keys.shift=false});
canvas.addEventListener("click",()=>{if(state.running&&!state.ended&&document.pointerLockElement!==canvas)canvas.requestPointerLock?.()});document.addEventListener("pointerlockchange",()=>{if(!state.running||state.ended)return;state.paused=document.pointerLockElement!==canvas;if(state.paused){interaction.textContent="DEVAM ETMEK İÇİN EKRANA TIKLA";interaction.classList.add("show")}else interaction.classList.remove("show")});pauseButton.addEventListener("click",()=>document.exitPointerLock?.());deployButton.addEventListener("click",startGame);replayButton.addEventListener("click",()=>location.reload());window.addEventListener("resize",()=>engine.resize());
engine.runRenderLoop(()=>{const dt=Math.min(engine.getDeltaTime()/1000,.034);updateGame(dt);scene.render()});updateHud();document.body.dataset.gameReady="true";
