export class TestMap {
  constructor(scene, navigation, profile) {
    this.scene = scene; this.navigation = navigation; this.profile = profile; this.materials = new Map(); this.shadowGenerator = null;
  }
  build() {
    this.scene.clearColor = new BABYLON.Color4(0.055, 0.065, 0.08, 1);
    this.scene.ambientColor = new BABYLON.Color3(0.23, 0.2, 0.3);
    this.scene.fogMode = BABYLON.Scene.FOGMODE_EXP2; this.scene.fogDensity = 0.011; this.scene.fogColor = new BABYLON.Color3(0.09, 0.1, 0.13);
    const hemi = new BABYLON.HemisphericLight("moon-fill", new BABYLON.Vector3(-0.3, 1, 0.2), this.scene); hemi.intensity = 0.85; hemi.diffuse = new BABYLON.Color3(0.56, 0.61, 0.78); hemi.groundColor = new BABYLON.Color3(0.12, 0.08, 0.15);
    const sun = new BABYLON.DirectionalLight("dusk-light", new BABYLON.Vector3(-0.55, -1, 0.42), this.scene); sun.position.set(18, 34, -22); sun.intensity = 1.35; sun.diffuse = new BABYLON.Color3(0.83, 0.7, 0.94);
    this.shadowGenerator = new BABYLON.ShadowGenerator(this.profile.shadows, sun); this.shadowGenerator.useBlurExponentialShadowMap = this.profile.shadows > 512; this.shadowGenerator.blurKernel = 18;

    const ground = BABYLON.MeshBuilder.CreateGround("tora-ground", { width: 80, height: 80, subdivisions: 2 }, this.scene); ground.material = this.#mat("moss-ground", "#283428", 0, .98); ground.receiveShadows = true; ground.checkCollisions = true; ground.metadata = { ground: true };
    for (let i = 0; i < 15; i++) { const path = BABYLON.MeshBuilder.CreateGround(`path-${i}`, { width: 7.4, height: 5.2 }, this.scene); path.position.set(Math.sin(i * .38) * 2.2, .012, -27 + i * 4.2); path.rotation.y = Math.sin(i * .7) * .09; path.material = this.#mat("earth-path", "#4b3b32", 0, 1); path.metadata = { ground: true }; }
    this.#buildRuins(); this.#buildCamp(); this.#buildForest(); this.#buildArena(); this.#buildBounds();
    return { spawn: new BABYLON.Vector3(0, 0, -18), shadowGenerator: this.shadowGenerator };
  }
  addShadowCaster(mesh) { if (mesh?.getChildMeshes) mesh.getChildMeshes(false).forEach((child) => { if (child instanceof BABYLON.AbstractMesh) this.shadowGenerator.addShadowCaster(child); }); }
  #mat(name, color, metallic = 0, roughness = .82, emissive = null) { if (this.materials.has(name)) return this.materials.get(name); const m = new BABYLON.PBRMaterial(name, this.scene); m.albedoColor = BABYLON.Color3.FromHexString(color); m.metallic = metallic; m.roughness = roughness; if (emissive) m.emissiveColor = BABYLON.Color3.FromHexString(emissive); this.materials.set(name, m); return m; }
  #stone(name, x, z, sx, sy, sz, rotation = 0) { const mesh = BABYLON.MeshBuilder.CreateBox(name, { size: 1 }, this.scene); mesh.position.set(x, sy / 2, z); mesh.scaling.set(sx, sy, sz); mesh.rotation.y = rotation; mesh.material = this.#mat("ancient-stone", "#4a4b54", .05, .94); mesh.checkCollisions = true; mesh.receiveShadows = true; this.shadowGenerator.addShadowCaster(mesh); this.navigation.addObstacle(x, z, Math.max(sx, sz) * .55); return mesh; }
  #buildRuins() { this.#stone("ruin-wall-a", -16, -3, 8, 3.4, .8, .18); this.#stone("ruin-wall-b", -19, 1, .8, 3, 7, -.12); this.#stone("ruin-arch-left", -9, 6, 1.1, 4.2, 1.2); this.#stone("ruin-arch-right", -4.6, 6, 1.1, 4.2, 1.2); this.#stone("ruin-arch-top", -6.8, 6, 5.2, .8, 1.15); }
  #buildCamp() { const fireMat = this.#mat("campfire", "#ff6a35", .05, .35, "#ff401c"); for (let i = 0; i < 7; i++) { const rock = BABYLON.MeshBuilder.CreatePolyhedron(`fire-ring-${i}`, { type: 1, size: .32 }, this.scene); const a = i / 7 * Math.PI * 2; rock.position.set(13 + Math.cos(a), .2, -8 + Math.sin(a)); rock.material = this.#mat("rock", "#373840", 0, 1); } const flame = BABYLON.MeshBuilder.CreatePolyhedron("campfire-flame", { type: 2, size: .7 }, this.scene); flame.position.set(13, .65, -8); flame.scaling.y = 1.5; flame.material = fireMat; const light = new BABYLON.PointLight("camp-light", new BABYLON.Vector3(13, 2, -8), this.scene); light.diffuse = new BABYLON.Color3(1, .36, .12); light.intensity = 2.2; light.range = 13; this.#stone("camp-crate", 16, -7, 1.3, 1.1, 1.3, .3); }
  #buildForest() { const trunkMat = this.#mat("tree-bark", "#29231f", 0, 1); const crownMat = this.#mat("dark-leaves", "#1c3228", 0, .95); const trunk = BABYLON.MeshBuilder.CreateCylinder("tree-trunk-source", { height: 3.8, diameterTop: .45, diameterBottom: .75, tessellation: 7 }, this.scene); trunk.material = trunkMat; const crown = BABYLON.MeshBuilder.CreatePolyhedron("tree-crown-source", { type: 2, size: 2.3 }, this.scene); crown.material = crownMat; const spots = [[-28,-19],[-23,-27],[-30,-4],[27,-20],[30,-8],[23,1],[-27,17],[-21,26],[27,23],[20,29]]; spots.forEach(([x,z], i) => { const t = i === 0 ? trunk : trunk.createInstance(`tree-trunk-${i}`); const c = i === 0 ? crown : crown.createInstance(`tree-crown-${i}`); t.position.set(x,1.9,z); c.position.set(x,4.6,z); const s=.85+(i%3)*.14; t.scaling.set(s,s,s); c.scaling.set(s,s,s); t.checkCollisions=true; this.navigation.addObstacle(x,z,.75*s); }); for (let i=0;i<22;i++){ const a=i*2.399; const r=17+(i%5)*4; const x=Math.cos(a)*r,z=Math.sin(a)*r; if(Math.abs(x)<6&&z<24)continue; const rock=BABYLON.MeshBuilder.CreatePolyhedron(`field-rock-${i}`,{type:1,size:.55+(i%4)*.12},this.scene); rock.position.set(x,.35,z); rock.scaling.y=.65; rock.rotation.y=a; rock.material=this.#mat("rock","#373840",0,1); this.navigation.addObstacle(x,z,.45); } }
  #buildArena() { const mat=this.#mat("column-stone","#55515d",.03,.9); for(let i=0;i<6;i++){const a=(i/6)*Math.PI*2;const x=Math.cos(a)*8,z=14+Math.sin(a)*8;const h=i%2?2.2:3.8;const col=BABYLON.MeshBuilder.CreateCylinder(`broken-column-${i}`,{height:h,diameter:1.1,tessellation:10},this.scene);col.position.set(x,h/2,z);col.rotation.z=(i-2.5)*.025;col.material=mat;col.checkCollisions=true;col.receiveShadows=true;this.shadowGenerator.addShadowCaster(col);this.navigation.addObstacle(x,z,.65);} const marker=BABYLON.MeshBuilder.CreateTorus("training-ring",{diameter:13,thickness:.12,tessellation:48},this.scene);marker.position.set(0,.05,14);marker.rotation.x=Math.PI/2;marker.material=this.#mat("arena-rune","#742fb0",.1,.6,"#32105a"); }
  #buildBounds() { for(let i=0;i<24;i++){const a=i/24*Math.PI*2,x=Math.cos(a)*39,z=Math.sin(a)*39;const monolith=BABYLON.MeshBuilder.CreatePolyhedron(`boundary-${i}`,{type:1,size:1.4},this.scene);monolith.position.set(x,.7,z);monolith.scaling.set(.7,1.6,.7);monolith.material=this.#mat("boundary-stone","#292631",.05,.9);monolith.freezeWorldMatrix();} }
}
