import { GAME_CONFIG, MOB_SPAWNS } from "./Config.js";
import { AssetManager } from "./AssetManager.js";
import { Navigation } from "../world/Navigation.js";
import { TestMap } from "../world/TestMap.js";
import { InputManager } from "../input/InputManager.js";
import { CursorManager } from "../input/CursorManager.js";
import { ThirdPersonCamera } from "../camera/ThirdPersonCamera.js";
import { PlayerController } from "../player/PlayerController.js";
import { PlayerAnimator } from "../player/PlayerAnimator.js";
import { EntityManager } from "../entities/EntityManager.js";
import { CombatSystem } from "../combat/CombatSystem.js";
import { NetworkAdapter } from "../network/NetworkAdapter.js";
import { HUD } from "../ui/HUD.js";
import { ProgressionSystem } from "../progression/ProgressionSystem.js";

export class Game {
  constructor(runtime,onProgress=()=>{}){this.runtime=runtime;this.engine=runtime.engine;this.canvas=runtime.canvas;this.onProgress=onProgress;this.scene=null;this.running=false;this.paused=false;this.snapshotTimer=0;this.lastTime=performance.now();}
  async initialize(){this.onProgress(28,"Yerel dünya oturumu açılıyor…");this.network=new NetworkAdapter();await this.network.connect();this.scene=new BABYLON.Scene(this.engine);this.scene.collisionsEnabled=true;this.navigation=new Navigation(GAME_CONFIG.mapHalfSize);const assets=new AssetManager(this.scene,GAME_CONFIG,this.onProgress);await assets.initialize();this.map=new TestMap(this.scene,this.navigation,this.runtime.profile);const world=await this.map.build(assets);this.onProgress(68,"Savaşçı ve düşmanlar hazırlanıyor…");const visual=await assets.loadPlayerVisual();const mobVisuals=await Promise.all(MOB_SPAWNS.map((_,index)=>assets.instantiateMob(index)));this.input=new InputManager(this.canvas);this.player=new PlayerController(visual,this.input,this.navigation);this.player.position.copyFrom(world.spawn);this.progression=new ProgressionSystem(this.player);this.animator=new PlayerAnimator(visual);this.camera=new ThirdPersonCamera(this.scene,this.canvas,this.player.root);this.entities=new EntityManager(this.scene,this.navigation,MOB_SPAWNS,(entity,result)=>this.combat?.damagePlayer(result),mobVisuals);this.combat=new CombatSystem(this.scene,this.player,this.animator,this.entities,{onDamage:(entity,result)=>this.hud?.showDamage(entity,result),onKill:(mob)=>this.#onMobDefeated(mob),onStatus:(message)=>this.hud?.setStatus(message)});this.hud=new HUD(this.scene,this.engine,this.player,this.entities,this.combat.skills,this.progression,(slot)=>this.#useSkill(slot));this.cursor=new CursorManager(this.scene,this.canvas,this.player,this.entities);this.hud.setDebug(GAME_CONFIG.debug);this.map.addShadowCaster(this.player.root);this.entities.mobs.forEach(mob=>this.map.addShadowCaster(mob.root));this.#bindInput();this.#bindPauseMenu();this.onProgress(92,"Arayüz ve savaş sistemi bağlanıyor…");this.scene.executeWhenReady(()=>this.onProgress(100,"Dünya hazır."));this.runtime.run(()=>this.#frame());return{backend:this.runtime.backend};}
  enter(){this.running=true;this.paused=false;this.input.enabled=true;this.hud.show(true);document.getElementById("pause-menu").hidden=true;this.canvas.focus();this.lastTime=performance.now();}
  leave(){this.running=false;this.paused=false;this.input.enabled=false;this.hud.show(false);document.getElementById("pause-menu").hidden=true;}
  togglePause(force){if(!this.running)return;this.paused=typeof force==="boolean"?force:!this.paused;this.input.enabled=!this.paused;document.getElementById("pause-menu").hidden=!this.paused;}
  applyQuality(name){this.runtime.applyQuality(name);}
  #bindInput(){this.input.onEscape=()=>this.togglePause();this.input.onTab=()=>{this.entities.cycle(this.player.position);};this.input.onSkill=(slot)=>this.#useSkill(slot);this.scene.onPointerObservable.add((info)=>{if(!this.running||this.paused||info.type!==BABYLON.PointerEventTypes.POINTERDOWN||info.event.button!==0)return;const actionPick=this.scene.pick(this.scene.pointerX,this.scene.pointerY,(mesh)=>Boolean(mesh.metadata?.mob||mesh.metadata?.npc||mesh.metadata?.loot||mesh.metadata?.interactive));if(actionPick?.hit){const data=actionPick.pickedMesh.metadata;if(data.mob){const mob=this.entities.getById(data.entityId);this.entities.select(mob);this.combat.basicAttack(mob,this.camera.forwardOnGround());}else if(data.npc)this.hud.addChat("Demirci Ayame", "Kuzeydeki harabelerde iblis izleri gördüm. Kılıcını keskin tut.");else if(data.loot)this.hud.setStatus("Sandık mühürlü. Anahtar harabe muhafızında olabilir.");else this.hud.setStatus("Demirci tezgâhı: ekipman geliştirme yakında.");return;}const groundPick=this.scene.pick(this.scene.pointerX,this.scene.pointerY,(mesh)=>Boolean(mesh.metadata?.ground));if(groundPick?.hit){this.entities.clear();this.player.targetId=null;this.player.setDestination(groundPick.pickedPoint,.18);}});}
  #bindPauseMenu(){document.getElementById("resume-button").addEventListener("click",()=>this.togglePause(false));document.getElementById("pause-quality").addEventListener("change",event=>{window.ToraMenu.applyQuality(event.target.value,true);this.applyQuality(event.target.value);});document.getElementById("exit-button").addEventListener("click",()=>{this.leave();document.getElementById("menu-screen").classList.remove("is-leaving");window.ToraMenu.unlock();});}
  #useSkill(slot){if(!this.running||this.paused)return;this.combat.useSkill(slot,this.entities.selected,this.camera.forwardOnGround());}
  #onMobDefeated(mob){const result=this.progression.recordDefeat(mob);if(!result)return;this.hud.announceProgress(result);if(result.questCompleted)this.hud.setStatus("İlk Sınav tamamlandı. Bozkır seni artık tanıyor.");else this.hud.setStatus(`${mob.name} yenildi • +${result.killXp} XP`);}
  #frame(){const now=performance.now(),dt=Math.min(.05,(now-this.lastTime)/1000||.016);this.lastTime=now;if(this.running&&!this.paused){this.combat.update(dt);this.player.update(dt,this.camera);this.animator.setState(this.player.state);this.animator.update(dt,this.player.speedRatio);this.camera.update(dt);this.entities.update(dt,this.player);if(this.player.alive)this.player.mana=Math.min(this.player.maxMana,this.player.mana+4*dt);this.snapshotTimer+=dt;if(this.snapshotTimer>.25){this.network.publishSnapshot([this.player,...this.entities.mobs]);this.snapshotTimer=0;}this.hud.update();this.input.endFrame();}this.scene.render();}
}
