export class PlayerCombat {
  constructor(player, animator, entities, skillSystem, callbacks = {}) {
    this.player=player;this.animator=animator;this.entities=entities;this.skills=skillSystem;this.callbacks=callbacks;
    this.pending=null;this.active=null;this.elapsed=0;this.applied=new Set();this.fallbackDirection=new BABYLON.Vector3(0,0,1);
  }
  request(slot,target,fallbackDirection){const skill=this.skills.get(slot);if(!skill||this.active||this.pending)return false;const check=this.skills.canUse(skill,this.player);if(!check.ok){this.callbacks.onStatus?.(check.reason);return false;}this.fallbackDirection=fallbackDirection?.clone()||this.fallbackDirection;if(skill.instant)return this.#instant(skill,target);if(!skill.aoe&&!target){this.callbacks.onStatus?.("Önce bir hedef seç.");return false;}this.pending={skill,target};this.player.targetId=target?.id||null;return true;}
  requestBasic(target,fallbackDirection){return this.request(1,target,fallbackDirection);}
  update(dt){if(this.active){this.elapsed+=dt;this.active.skill.impact?.forEach((moment,index)=>{if(this.elapsed>=moment&&!this.applied.has(index)){this.applied.add(index);this.#impact(this.active.skill,this.active.target,index);}});if(this.elapsed>=this.active.skill.duration){this.active=null;this.elapsed=0;this.applied.clear();this.player.state="idle";this.animator.setState("idle");}return;}if(!this.pending)return;const {skill,target}=this.pending;if(!skill.aoe&&(!target||!target.alive)){this.pending=null;this.player.targetId=null;return;}const distance=target?BABYLON.Vector3.Distance(this.player.position,target.position):0;if(target&&distance>skill.range){const dir=target.position.subtract(this.player.position);dir.y=0;const destination=target.position.subtract(dir.normalize().scale(Math.max(1.8,skill.range-.35)));this.player.setDestination(destination,.25);return;}this.player.cancelDestination();if(target)this.player.face(target.position);const commit=this.skills.commit(skill,this.player);if(!commit.ok){this.callbacks.onStatus?.(commit.reason);this.pending=null;return;}this.active=this.pending;this.pending=null;this.elapsed=0;this.applied.clear();const state=skill.slot<=2?`attack${skill.slot}`:(skill.slot===3||skill.slot===9?"heavy":"skill");this.player.state=state;this.animator.setState(state);this.callbacks.onCast?.(skill,this.player.position,target?.position);}
  #instant(skill,target){const commit=this.skills.commit(skill,this.player);if(!commit.ok){this.callbacks.onStatus?.(commit.reason);return false;}if(skill.instant==="dash"){let direction=target?.position.subtract(this.player.position)||this.fallbackDirection.clone();direction.y=0;this.player.dash(direction);this.callbacks.onCast?.(skill,this.player.position,target?.position);}if(skill.instant==="guard"){this.player.buffs.guard=6;this.callbacks.onStatus?.("Savaşçı Savunması aktif: alınan hasar azaldı.");}if(skill.instant==="rage"){this.player.buffs.rage=8;this.callbacks.onStatus?.("Öfke aktif: saldırı ve hareket hızı arttı.");}return true;}
  #impact(skill,target,index){const victims=skill.aoe?this.entities.inRadius(this.player.position,skill.range):(target?.alive?[target]:[]);for(const mob of victims){const damage=Math.round(skill.damage*(index>0?.75:1));const result=mob.takeHit(this.player,damage);if(result){this.callbacks.onDamage?.(mob,result,skill);if(!mob.alive)this.callbacks.onKill?.(mob,skill);}}this.callbacks.onImpact?.(skill,this.player.position,target?.position);}
}
